language: objective-c
osx_image: xcode8
matrix:
  include:
    - script: make test
      env: JOB=Xcode
    - script: swift build && swift test
      env: JOB=SPM
git:
  submodules: false
branches:
  only:
    - master
notifications:
  email: false
  slack: realmio:vPdpsG9NLDo2DNlbqtcMAQuE
